---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-hkmdxlftjf-io-v1alpha1-agent
  failurePolicy: Fail
  name: vagent-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.hkmdxlftjf.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agents
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-hkmdxlftjf-io-v1alpha1-tool
  failurePolicy: Fail
  name: vtool-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.hkmdxlftjf.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tools
  sideEffects: None
