---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.hkmdxlftjf.io
  resources:
  - agentclasses
  - agents
  - credentials
  - knowledgebases
  - mcpservers
  - memories
  - models
  - policies
  - prompttemplates
  - skills
  - toolpolicies
  - tools
  - toolsets
  - triggers
  - workflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.hkmdxlftjf.io
  resources:
  - agentclasses/status
  - agents/status
  - credentials/status
  - knowledgebases/status
  - mcpservers/status
  - memories/status
  - models/status
  - policies/status
  - prompttemplates/status
  - skills/status
  - toolpolicies/status
  - tools/status
  - toolsets/status
  - triggers/status
  - workflows/status
  verbs:
  - get
  - patch
  - update
